# Generated by Django 4.0.3 on 2022-07-28 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggested', models.BooleanField()),
                ('user_item', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packed_api.category')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packed_api.condition')),
            ],
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Packing List', max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('departure_date', models.CharField(blank=True, max_length=10)),
                ('return_date', models.CharField(blank=True, max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('destination_city', models.CharField(blank=True, max_length=70)),
                ('destination_country', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PackingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('packed', models.BooleanField(default=False)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='packed_api.item')),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packed_api.packinglist')),
            ],
        ),
    ]
