# Generated by Django 4.0.3 on 2022-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='a', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
