# Generated by Django 4.0.3 on 2022-07-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglistitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
