# Generated by Django 4.0.3 on 2022-07-15 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0002_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suggested', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('travel_date', models.DateField()),
                ('completed', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
        migrations.CreateModel(
            name='PackingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list_item', to='packed_api.item')),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list', to='packed_api.packinglist')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packed_api.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.ManyToManyField(to='packed_api.condition'),
        ),
    ]
