# Generated by Django 4.0.3 on 2022-07-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0002_alter_packinglistitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_item',
        ),
    ]
