# Generated by Django 4.0.3 on 2022-08-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0002_packinglistitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinglistitem',
            name='title',
        ),
    ]
