# Generated by Django 4.0.3 on 2022-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0003_condition_item_packinglist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_item',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='owner',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
