# Generated by Django 4.0.3 on 2022-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0004_item_user_item_packinglistitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_item',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
