# Generated by Django 4.0.3 on 2022-08-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0005_packinglist_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
