# Generated by Django 4.0.3 on 2022-07-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0005_alter_item_user_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='packinglist',
            old_name='name',
            new_name='packing_list_name',
        ),
    ]
