# Generated by Django 4.0.3 on 2022-07-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packed_api', '0006_rename_name_item_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packed_api.condition'),
            preserve_default=False,
        ),
    ]
