stages:
  - test
  # - build

services:
  - postgres:14.2-bullseye

variables:
  POSTGRES_PASSWORD: test
  DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres

# TEST
weather-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd api/weather
    - pip install -r requirements.txt
    - python -m pytest

locations-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd api/locations
    - pip install -r requirements.txt
    - python -m pytest

currency-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd api/currency
    - pip install -r requirements.txt
    # - python -m pytest, still working on one unit test

service-name-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd packing-lists
    - pip install -r requirements.txt
    - python manage.py test
  
# lint-test-job:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - pip install flake8
#     - flake8 api  # Run flake8 on Python project to check
#                   # for code quality

# BUILD
# front-end-build-job:
#   stage: build
#   image: node:lts-bullseye
#   needs:
#     - api-unit-test-job  # These two jobs must succeed for
#     - lint-test-job      # this build-job to run
#   script:
#     - cd ghi
#     - npm install
#     - npm run build  # Build the React application
# --------CURRENCY------------------------------------------
